spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: default
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false


